title: OH1 Apps
logo: /assets/img/logo.png
description: coding for fun
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
github:
  zip_url: http://example.com/download.zip
  another_url: another value
